<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OilBatchRefineryTank;
use App\Models\OilBatchRefineryReading;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class OilBatchRefineryReadingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info('Starting historical Batch Refinery readings seeder...');

        // Ambil semua master tangki yang aktif
        $tanks = OilBatchRefineryTank::where('is_active', true)->get();

        if ($tanks->isEmpty()) {
            $this->command->error('No master tanks found. Please run OilBatchRefinerySeeder first.');
            return;
        }

        // Tentukan rentang tanggal: 30 hari lalu sampai kemarin
        $endDate = Carbon::yesterday();
        $startDate = $endDate->copy()->subDays(29);

        // Hapus data lama di rentang ini agar seeder bisa dijalankan ulang tanpa duplikasi
        $this->command->warn("Deleting existing readings from {$startDate->toDateString()} to {$endDate->toDateString()}...");
        OilBatchRefineryReading::whereBetween('reading_date', [$startDate, $endDate])->delete();

        $readingsToInsert = [];

        // Loop untuk setiap hari
        for ($date = $startDate->copy(); $date->lte($endDate); $date->addDay()) {
            
            // Loop untuk setiap tangki
            foreach ($tanks as $tank) {
                // Buat data acak yang realistis
                $capacity = $tank->capacity_kg;
                
                // Nilai stok antara 20% s/d 95% dari kapasitas
                $currentValue = round($capacity * (mt_rand(2000, 9500) / 10000), 2);

                // Status acak
                $statuses = ['Process', 'Hold', 'Release'];
                $status = $statuses[array_rand($statuses)];
                
                // Suhu acak (misal: antara 45.0 - 120.5 C)
                $temperature = mt_rand(450, 1205) / 10;
                
                // Gauge acak (misal: antara 0.5 - 4.5 m)
                $gauge = mt_rand(50, 450) / 100;

                // Siapkan data untuk bulk insert
                $readingsToInsert[] = [
                    'tank_id' => $tank->id,
                    'reading_date' => $date->toDateString(),
                    'current_value_kg' => $currentValue,
                    'temperature' => $temperature,
                    'gauge_board' => $gauge,
                    'oil_code' => 'CPO-SEED',
                    'description' => 'Auto-generated by seeder',
                    'status' => $status,
                    'created_by' => 'Seeder',
                    'created_at' => $date,
                    'updated_at' => $date,
                ];
            }
        }

        // Gunakan bulk insert untuk performa yang jauh lebih cepat
        $this->command->info("Preparing to insert " . count($readingsToInsert) . " records...");

        // Insert data dalam chunk (potongan) untuk menghindari masalah memori
        foreach (array_chunk($readingsToInsert, 500) as $chunk) {
            DB::table('oil_batch_refinery_readings')->insert($chunk);
        }

        $this->command->info('Historical Batch Refinery readings seeding completed successfully!');
    }
}